version: "2"
services:
  app:
    build: ./app
    links:
      - db
    volumes:
      - ./app:/app/
    ports:
      - "8090:5000"

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
